/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Mục sư Nguyễn  Hữu Bình',
      items: [
        'muc-su-nguyen-huu-binh/de-tro-nen-giong-chua',
        'muc-su-nguyen-huu-binh/giong-chua-trong-dan-than-phuc-vu',
        'muc-su-nguyen-huu-binh/khong-gi-phai-so-hai',
        'muc-su-nguyen-huu-binh/song-ket-qua-cho-chua',
        'muc-su-nguyen-huu-binh/vuot-qua-thach-thuc',
      ],
    },
     {
      type: 'category',
      label: 'Mục sư Phan Vĩnh Cự',
      items: [
        'muc-su-phan-vinh-cu/chua-song-vi-toi',
        'muc-su-phan-vinh-cu/hanh-trinh-phuoc-hanh',
        'muc-su-phan-vinh-cu/the-he-tiep-noi',
      ],
    },
    {
      type: 'category',
      label: 'Mục sư Mã Phúc Hiệp',
      items: [
        'ms-ma-phuc-hiep/hay-nho-lai-vo-cua-lot',
        'ms-ma-phuc-hiep/phuoc-hanh-noi-chua-thang-thien',
        'ms-ma-phuc-hiep/1',
        'ms-ma-phuc-hiep/2',
        'ms-ma-phuc-hiep/3',
        'ms-ma-phuc-hiep/4',
        'ms-ma-phuc-hiep/5',
        'ms-ma-phuc-hiep/6',
        'ms-ma-phuc-hiep/7',

      ],
    },
  ],
  boilinhSidebar: [
    {
      type: 'category',
      label: 'Hôn nhân và gia đình',
      items: [
        'boi-linh-hon-nhan-gia-dinh/p1',
        'boi-linh-hon-nhan-gia-dinh/p2',
        'boi-linh-hon-nhan-gia-dinh/p3',
        'boi-linh-hon-nhan-gia-dinh/p4',
      ]
    },
    {
      type: 'category',
      label: 'Con Người & Chức Vụ Của Ba-na-ba',
      items: [
        'boi-linh-con-nguoi-chuc-vu/p1',
        'boi-linh-con-nguoi-chuc-vu/p2',
        
      ]
    },
    {
      type: 'category',
      label: 'Cuộc đời Chúa Giê-xu',
      items: [
        'boi-linh-cuoc-doi-chua-giexu/p1',
        'boi-linh-cuoc-doi-chua-giexu/p2',
        'boi-linh-cuoc-doi-chua-giexu/p3',
        'boi-linh-cuoc-doi-chua-giexu/p4',
        'boi-linh-cuoc-doi-chua-giexu/p5',
        'boi-linh-cuoc-doi-chua-giexu/p6',
      ]
    },
    {
      type: 'category',
      label: 'Khảo Học Thánh Kinh',
      items: [
        'boi-linh-khao-hoc-thanh-kinh/p1',
        'boi-linh-khao-hoc-thanh-kinh/p2',
        'boi-linh-khao-hoc-thanh-kinh/p3',
        'boi-linh-khao-hoc-thanh-kinh/p4',
      ]
    },
    {
      type: 'category',
      label: 'Sống Đạo Giữa Đời',
      items: [
        'boi-linh-song-dao-giua-doi/p1',
        'boi-linh-song-dao-giua-doi/p2',
        'boi-linh-song-dao-giua-doi/p3',
  
      ]
    },
    {
      type: 'category',
      label: 'Sách Giô-na',
      items: [
        'boi-linh-sach-gio-na/p1',
        'boi-linh-sach-gio-na/p2',
        'boi-linh-sach-gio-na/p3',
        'boi-linh-sach-gio-na/p4',
        'boi-linh-sach-gio-na/p5',
        'boi-linh-sach-gio-na/p6',
        
      ]
    },
    {
      type: 'category',
      label: 'Sách Khải Huyền',
      items: [
        'boi-linh-khai-huyen/p1',
        'boi-linh-khai-huyen/p2',
        'boi-linh-khai-huyen/p3',
        'boi-linh-khai-huyen/p4',
        'boi-linh-khai-huyen/p5',
        'boi-linh-khai-huyen/p6',
        'boi-linh-khai-huyen/p7',
        'boi-linh-khai-huyen/p8',
        'boi-linh-khai-huyen/p9',
      ]
    },
  ]

 

};

export default sidebars;
