/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Mục sư Nguyễn  Hữu Bình',
      items: [
        'muc-su-nguyen-huu-binh/de-tro-nen-giong-chua',
        'muc-su-nguyen-huu-binh/giong-chua-trong-dan-than-phuc-vu',
        'muc-su-nguyen-huu-binh/khong-gi-phai-so-hai',
        'muc-su-nguyen-huu-binh/song-ket-qua-cho-chua',
        'muc-su-nguyen-huu-binh/vuot-qua-thach-thuc',
      ],
    },
     {
      type: 'category',
      label: 'Mục sư Phan Vĩnh Cự',
      items: [
        'muc-su-phan-vinh-cu/chua-song-vi-toi',
        'muc-su-phan-vinh-cu/hanh-trinh-phuoc-hanh',
        'muc-su-phan-vinh-cu/the-he-tiep-noi',
      ],
    },
  ],
  boilinhSidebar: [
    {
      type: 'category',
      label: 'Hôn nhân và gia đình',
      items: [
        'boi-linh-hon-nhan-gia-dinh/p1',
        'boi-linh-hon-nhan-gia-dinh/p2',
        'boi-linh-hon-nhan-gia-dinh/p3',
        'boi-linh-hon-nhan-gia-dinh/p4',
      ]
    },
    {
      type: 'category',
      label: 'Sách Giô-na',
      items: [
        'boi-linh-sach-gio-na/p1',
        'boi-linh-sach-gio-na/p2',
        'boi-linh-sach-gio-na/p3',
        'boi-linh-sach-gio-na/p4',
        'boi-linh-sach-gio-na/p5',
        'boi-linh-sach-gio-na/p6',
        
      ]
    },
  ]

 

};

export default sidebars;
